import { useState, type FormEvent } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Coins, Sparkles, X } from 'lucide-react'
import { DIFFICULTY_LABELS, DIFFICULTY_REWARDS, FREQUENCY_LABELS, TASK_CATEGORIES, WEEK_DAYS } from '../../constants/tasks'
import type { HabitTask, TaskDifficulty, TaskFrequency, TaskInput } from '../../types/tasks'

export function TaskFormModal({ open, task, busy, onClose, onSave }: { open: boolean; task: HabitTask | null; busy: boolean; onClose: () => void; onSave: (input: TaskInput) => Promise<void> }) {
  const [title, setTitle] = useState(task?.title ?? ''); const [description, setDescription] = useState(task?.description ?? ''); const [category, setCategory] = useState<string>(task?.category ?? TASK_CATEGORIES[0]); const [difficulty, setDifficulty] = useState<TaskDifficulty>(task?.difficulty ?? 'common'); const [frequency, setFrequency] = useState<TaskFrequency>(task?.frequency ?? 'daily'); const [weekDays, setWeekDays] = useState<number[]>(task?.weekDays ?? []); const [dueDate, setDueDate] = useState(task?.dueDate ? task.dueDate.toDate().toISOString().slice(0, 10) : '')
  async function submit(event: FormEvent) { event.preventDefault(); await onSave({ title, description, category, difficulty, frequency, weekDays, dueDate: dueDate ? new Date(`${dueDate}T12:00:00`) : null, isActive: task?.isActive ?? true }) }
  const reward = DIFFICULTY_REWARDS[difficulty]
  return <AnimatePresence>{open && <motion.div className="game-modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={event => { if (event.target === event.currentTarget && !busy) onClose() }}><motion.section role="dialog" aria-modal="true" aria-labelledby="task-form-title" initial={{ opacity: 0, y: 25, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 15 }} className="task-form-modal"><button className="modal-close" onClick={onClose} disabled={busy} aria-label="Fechar"><X size={19} /></button><span className="eyebrow"><Sparkles size={13} />Forjar objetivo</span><h2 id="task-form-title" className="section-heading mt-1">{task ? 'Editar missão' : 'Nova missão'}</h2><form onSubmit={submit} className="task-form"><label>Título<input value={title} onChange={event => setTitle(event.target.value)} minLength={2} maxLength={80} required placeholder="Ex: Meditar por 15 minutos" /></label><label>Descrição<textarea value={description} onChange={event => setDescription(event.target.value)} maxLength={240} rows={3} placeholder="O que precisa ser feito?" /></label><div className="task-form-grid"><label>Categoria<select value={category} onChange={event => setCategory(event.target.value)}>{TASK_CATEGORIES.map(value => <option key={value}>{value}</option>)}</select></label><label>Frequência<select value={frequency} onChange={event => setFrequency(event.target.value as TaskFrequency)}>{Object.entries(FREQUENCY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><label>Dificuldade<div className="difficulty-selector">{(Object.keys(DIFFICULTY_LABELS) as TaskDifficulty[]).map(value => <button type="button" key={value} className={difficulty === value ? 'selected' : ''} data-rarity={value} onClick={() => setDifficulty(value)}>{DIFFICULTY_LABELS[value]}</button>)}</div></label>{frequency === 'weekly' && <label>Dias da semana<div className="weekday-selector">{WEEK_DAYS.map((day, index) => <button type="button" key={day} className={weekDays.includes(index) ? 'selected' : ''} onClick={() => setWeekDays(days => days.includes(index) ? days.filter(value => value !== index) : [...days, index])}>{day}</button>)}</div></label>}{frequency === 'once' && <label>Prazo opcional<input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} /></label>}<div className="form-reward"><span>Recompensa definida pela dificuldade</span><strong><Sparkles size={14} />+{reward.xp} XP</strong><strong><Coins size={14} />+{reward.gold}</strong></div><button className="auth-submit mt-1" disabled={busy || (frequency === 'weekly' && weekDays.length === 0)}>{busy ? 'Selando missão...' : task ? 'Salvar alterações' : 'Criar missão'}</button></form></motion.section></motion.div>}</AnimatePresence>
}
