import { motion } from 'framer-motion'
import { BookOpen, Check, Dumbbell, Flame, Pencil, Power, Sparkles, Target, Trash2 } from 'lucide-react'
import { DIFFICULTY_LABELS, FREQUENCY_LABELS } from '../../constants/tasks'
import type { HabitTask } from '../../types/tasks'

const categoryIcons = { 'Exercício': Dumbbell, 'Estudos': BookOpen, 'Foco': Target, 'Bem-estar': Flame }

export function TaskManagementCard({ task, busy, completed, onComplete, onEdit, onDelete, onToggle }: { task: HabitTask; busy: boolean; completed: boolean; onComplete: () => void; onEdit: () => void; onDelete: () => void; onToggle: () => void }) {
  const Icon = categoryIcons[task.category as keyof typeof categoryIcons] ?? Target
  return <motion.article layout initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} whileHover={{ y: -3 }} className={`managed-task rarity-${task.difficulty} ${!task.isActive ? 'inactive' : ''} ${completed ? 'completed' : ''}`}><div className="managed-task-top"><div className="managed-task-icon"><Icon size={23} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className={`task-rarity ${task.difficulty}`}>{DIFFICULTY_LABELS[task.difficulty]}</span><span className="task-frequency">{FREQUENCY_LABELS[task.frequency]}</span>{!task.isActive && <span className="task-paused">Pausada</span>}{completed && <span className="task-completed-badge">Concluída</span>}</div><h3>{task.title}</h3><p>{task.description || 'Uma missão sem descrição, envolta em mistério.'}</p></div></div><div className="managed-task-footer"><div className="flex gap-3"><strong className="text-purple-300">✦ +{task.xpReward} XP</strong><strong className="text-gold">● +{task.goldReward}</strong></div><div className="task-actions"><button type="button" onClick={onToggle} disabled={busy} title={task.isActive ? 'Pausar missão' : 'Ativar missão'} aria-label={task.isActive ? 'Pausar missão' : 'Ativar missão'}><Power size={16} /></button><button type="button" onClick={onEdit} disabled={busy} title="Editar missão" aria-label="Editar missão"><Pencil size={16} /></button><button type="button" onClick={onDelete} disabled={busy} title="Excluir missão" aria-label="Excluir missão" className="danger"><Trash2 size={16} /></button></div></div><button onClick={onComplete} disabled={busy || completed || !task.isActive} className="complete-task-button">{busy ? <><Sparkles className="animate-spin" size={16} />Concedendo recompensa...</> : completed ? <><Check size={17} />Missão concluída</> : <><Sparkles size={16} />Completar missão</>}</button></motion.article>
}
