import { useState } from 'react'
import { Check, Package } from 'lucide-react'
import { ITEM_CATEGORY_LABELS, ITEM_RARITY_LABELS } from '../constants/store'
import { useAuth } from '../contexts/auth-context'
import { useInventory } from '../hooks/useInventory'
import { equipItem, unequipItem } from '../services/inventoryService'
import { getFriendlyFirebaseError } from '../utils/firebaseErrors'

export function InventoryPage() { const { user } = useAuth(); const { items, loading, error } = useInventory(); const [busy, setBusy] = useState<string | null>(null); const [actionMessage, setActionMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null); async function toggle(itemId: string, equipped: boolean) { if (!user) return; setBusy(itemId); setActionMessage(null); try { if (equipped) await unequipItem(user.uid, itemId); else await equipItem(user.uid, itemId); setActionMessage({ type: 'success', text: equipped ? 'Item desequipado.' : 'Item equipado no avatar.' }) } catch (cause) { setActionMessage({ type: 'error', text: getFriendlyFirebaseError(cause) }) } finally { setBusy(null) } }
  return <main className="inventory-page"><header><span className="eyebrow"><Package size={15} />Tesouro pessoal</span><h1>Inventário</h1><p>Artefatos conquistados e adquiridos durante sua jornada.</p></header>{(error || actionMessage) && <div role="status" className={`hero-message ${actionMessage?.type ?? 'error'}`}>{error || actionMessage?.text}</div>}{loading ? <div className="store-grid"><div className="store-skeleton" /><div className="store-skeleton" /></div> : items.length ? <section className="inventory-grid">{items.map(item => <article key={item.id} className={`inventory-card rarity-${item.rarity} ${item.equipped ? 'equipped' : ''}`}><div><img src={item.imageUrl} alt={item.name} />{item.equipped && <span><Check size={13} />Equipado</span>}</div><span>{ITEM_RARITY_LABELS[item.rarity]} · {ITEM_CATEGORY_LABELS[item.category]}</span><h2>{item.name}</h2><p>Adquirido por {item.purchasedPrice} ouro</p><button onClick={() => void toggle(item.id, item.equipped)} disabled={busy === item.id}>{busy === item.id ? 'Atualizando...' : item.equipped ? 'Desequipar' : 'Equipar'}</button></article>)}</section> : <section className="tasks-empty"><Package size={38} className="text-gold" /><h2>Seu inventário está vazio</h2><p>Visite o mercado para encontrar seus primeiros artefatos.</p></section>}</main>
}
