import { useMemo, useState } from 'react'
import { Coins, Filter, Search, ShoppingBag, Sparkles } from 'lucide-react'
import { PurchaseSuccessModal } from '../components/store/PurchaseSuccessModal'
import { StoreItemCard } from '../components/store/StoreItemCard'
import { ITEM_CATEGORY_LABELS, ITEM_RARITY_LABELS } from '../constants/store'
import { useAuth } from '../contexts/auth-context'
import { usePlayer } from '../contexts/player-context'
import { useInventory } from '../hooks/useInventory'
import { useStoreItems } from '../hooks/useStoreItems'
import { purchaseItem } from '../services/storeService'
import { equipItem } from '../services/inventoryService'
import type { ItemCategory, ItemRarity, PurchaseResult } from '../types/store'
import { getFriendlyFirebaseError } from '../utils/firebaseErrors'

export function MarketPage() { const { user } = useAuth(); const { player } = usePlayer(); const { items, loading, error } = useStoreItems(); const { items: inventory } = useInventory(); const [category, setCategory] = useState<'all' | ItemCategory>('all'); const [rarity, setRarity] = useState<'all' | ItemRarity>('all'); const [sort, setSort] = useState<'asc' | 'desc'>('asc'); const [search, setSearch] = useState(''); const [busy, setBusy] = useState<string | null>(null); const [equipping, setEquipping] = useState(false); const [purchase, setPurchase] = useState<PurchaseResult | null>(null); const [actionError, setActionError] = useState<string | null>(null); const ownedIds = useMemo(() => new Set(inventory.map(item => item.itemId)), [inventory]); const filtered = useMemo(() => items.filter(item => item.isAvailable && (category === 'all' || item.category === category) && (rarity === 'all' || item.rarity === rarity) && item.name.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === 'asc' ? a.price - b.price : b.price - a.price), [items, category, rarity, search, sort]); async function buy(itemId: string) { if (!user || busy) return; setBusy(itemId); setActionError(null); try { setPurchase(await purchaseItem(user.uid, itemId)) } catch (cause) { setActionError(getFriendlyFirebaseError(cause)) } finally { setBusy(null) } } async function equipPurchase() { if (!user || !purchase || equipping) return; setEquipping(true); setActionError(null); try { await equipItem(user.uid, purchase.item.id); setPurchase(null) } catch (cause) { setActionError(getFriendlyFirebaseError(cause)) } finally { setEquipping(false) } }
  return <main className="market-page"><header className="market-hero"><div className="market-merchant"><div><span>◉</span><span>◉</span></div><ShoppingBag size={36} /></div><div><span className="eyebrow">Bazar do mercador errante</span><h1>Mercado do Reino</h1><p>“Escolha com sabedoria, aventureiro. Cada artefato carrega uma história.”</p></div><div className="market-wallet"><span>Seu tesouro</span><strong><Coins />{player?.gold ?? 0}</strong></div></header><section className="market-filters"><div><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar artefato..." /></div><label><Filter size={15} /><select value={category} onChange={event => setCategory(event.target.value as 'all' | ItemCategory)}><option value="all">Todas as categorias</option>{Object.entries(ITEM_CATEGORY_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><select value={rarity} onChange={event => setRarity(event.target.value as 'all' | ItemRarity)}><option value="all">Todas as raridades</option>{Object.entries(ITEM_RARITY_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><select value={sort} onChange={event => setSort(event.target.value as 'asc' | 'desc')}><option value="asc">Menor preço</option><option value="desc">Maior preço</option></select></section>{(error || actionError) && <div className="tasks-error">{error || actionError}</div>}{loading ? <div className="store-grid">{Array.from({ length: 6 }, (_, i) => <div className="store-skeleton" key={i} />)}</div> : filtered.length ? <section className="store-grid">{filtered.map(item => <StoreItemCard key={item.id} item={item} owned={ownedIds.has(item.id)} playerLevel={player?.level ?? 1} playerGold={player?.gold ?? 0} busy={busy === item.id} onPurchase={() => void buy(item.id)} />)}</section> : <section className="tasks-empty"><Sparkles className="text-gold" size={35} /><h2>Nenhum artefato encontrado</h2><p>O mercador ainda não possui itens com esses filtros.</p></section>}<PurchaseSuccessModal purchase={purchase} equipping={equipping} onEquip={() => void equipPurchase()} onClose={() => setPurchase(null)} /></main>
}
