import { useState, type FormEvent } from 'react'
import { Eye, EyeOff, Mail, UserRound } from 'lucide-react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { AuthLayout } from '../components/AuthLayout'
import { useAuth } from '../contexts/auth-context'
import { registerWithEmail } from '../services/authService'
import { getFriendlyFirebaseError } from '../utils/firebaseErrors'

export function RegisterPage() { const { user } = useAuth(); const navigate = useNavigate(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); if (user) return <Navigate to="/" replace />;
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { await registerWithEmail(name, email, password); navigate('/', { replace: true }) } catch (cause) { setError(getFriendlyFirebaseError(cause)) } finally { setLoading(false) } }
  return <AuthLayout eyebrow="Início da jornada" title="Crie sua Lenda" subtitle="Forje seu personagem e transforme cada hábito em uma aventura."><form onSubmit={submit} className="auth-form"><label>Nome do aventureiro<div className="auth-input"><UserRound size={17} /><input value={name} onChange={e => setName(e.target.value)} minLength={2} placeholder="Como devemos chamá-lo?" required autoComplete="name" /></div></label><label>E-mail<div className="auth-input"><Mail size={17} /><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="aventureiro@email.com" required autoComplete="email" /></div></label><label>Senha<div className="auth-input"><input type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} minLength={6} placeholder="Mínimo de 6 caracteres" required autoComplete="new-password" /><button type="button" onClick={() => setShowPassword(value => !value)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>{error && <p role="alert" className="auth-error">{error}</p>}<button disabled={loading} className="auth-submit">{loading ? 'Forjando personagem...' : 'Começar minha jornada'}</button></form><p className="auth-footer">Já possui uma lenda? <Link to="/login">Entrar no reino</Link></p></AuthLayout> }
