import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { Award, Coins, Sparkles, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { AchievementClaimResult, AchievementDefinition, AchievementView } from '../../types/achievements'
import { AchievementProgress } from './AchievementCard'
import { achievementRarityLabels } from '../../utils/achievementUtils'
function Shell({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { const reduced = useReducedMotion(); return <motion.div className="achievement-modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.section initial={reduced ? undefined : { opacity: 0, scale: .86, y: 25 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={reduced ? undefined : { opacity: 0, scale: .92 }} onClick={event => event.stopPropagation()}><button className="achievement-modal-close" onClick={onClose}><X /></button>{children}</motion.section></motion.div> }
export function AchievementDetailsModal({ achievement, onClose, onClaim, busy }: { achievement: AchievementView | null; onClose: () => void; onClaim: () => void; busy: boolean }) { return <AnimatePresence>{achievement && <Shell onClose={onClose}><div className={`modal-medal ${achievement.rarity}`}><Award /></div><span className="modal-kicker">{achievementRarityLabels[achievement.rarity]}</span><h2>{achievement.secret && !achievement.unlocked ? 'Conquista secreta' : achievement.name}</h2><p>{achievement.secret && !achievement.unlocked ? 'Continue sua jornada para descobrir.' : achievement.description}</p>{!(achievement.secret && !achievement.unlocked) && <AchievementProgress value={achievement.currentProgress} target={achievement.requirement.target} />}<div className="modal-rewards"><strong><Sparkles /> +{achievement.reward.xp} XP</strong><strong><Coins /> +{achievement.reward.gold} ouro</strong></div>{achievement.unlocked && !achievement.rewardClaimed && <button className="achievement-primary" disabled={busy} onClick={onClaim}>{busy ? 'Resgatando...' : 'Resgatar recompensa'}</button>}</Shell>}</AnimatePresence> }
export function AchievementUnlockModal({ achievement, onClose, onClaim }: { achievement: AchievementDefinition | null; onClose: () => void; onClaim: () => void }) { return <AnimatePresence>{achievement && <Shell onClose={onClose}><div className="unlock-rays" /><div className={`modal-medal ${achievement.rarity}`}><Award /></div><span className="modal-kicker">Conquista desbloqueada!</span><h2>{achievement.name}</h2><p>{achievement.description}</p><div className="modal-rewards"><strong><Sparkles /> +{achievement.reward.xp} XP</strong><strong><Coins /> +{achievement.reward.gold} ouro</strong></div><div className="modal-actions"><button className="achievement-primary" onClick={onClaim}>Resgatar agora</button><Link to="/conquistas" onClick={onClose}>Ver conquistas</Link><button onClick={onClose}>Continuar jornada</button></div></Shell>}</AnimatePresence> }
export function AchievementRewardModal({ result, onClose }: { result: AchievementClaimResult | null; onClose: () => void }) { return <AnimatePresence>{result && <Shell onClose={onClose}><div className="modal-medal legendary"><Sparkles /></div><span className="modal-kicker">Recompensa recebida</span><h2>{result.achievement.name}</h2><div className="modal-rewards"><strong>+{result.xpEarned} XP</strong><strong>+{result.goldEarned} ouro</strong></div>{result.levelsGained > 0 && <p>Você alcançou o nível {result.newLevel}!</p>}<button className="achievement-primary" onClick={onClose}>Continuar</button></Shell>}</AnimatePresence> }
export function AchievementEmptyState({ filtered = false }: { filtered?: boolean }) { return <div className="achievement-empty"><Award /><h2>{filtered ? 'Nenhuma medalha encontrada' : 'O salão ainda está vazio'}</h2><p>{filtered ? 'Altere os filtros para revelar outras conquistas.' : 'Execute o seed para revelar as conquistas do reino.'}</p></div> }
