import { motion } from 'framer-motion'
import { Coins, Lock, MessageCircle, ShoppingBag } from 'lucide-react'
import { hero, marketItems, rarity, type MarketItem } from '../data/gameData'
import { RarityBadge } from './GamePrimitives'

export function StoreItemCard({ item }: { item: MarketItem }) { const Icon = item.icon; const locked = item.level && item.level > hero.level; const style = rarity[item.rarity]; return <motion.article whileHover={{ y: -6 }} className={`store-item ${style.border}`} style={{ '--item-glow': style.glow } as React.CSSProperties}><div className="item-pedestal"><div className="item-aura" style={{ background: item.accent }} /><Icon size={53} strokeWidth={1.15} style={{ color: item.accent }} className="relative z-10 drop-shadow-2xl" />{locked && <span className="item-lock"><Lock size={12} /> Nv. {item.level}</span>}</div><RarityBadge value={item.rarity} /><h3 className="mt-2 truncate font-display text-sm font-bold text-parchment">{item.name}</h3><div className="mt-3 flex items-center justify-between"><span className="flex items-center gap-1 text-sm font-bold text-gold"><Coins size={14} />{item.price}</span><button className="text-[10px] font-bold uppercase tracking-wider text-mist hover:text-gold">Examinar</button></div></motion.article> }

export function MerchantPreview() { return <section className="merchant-panel"><div className="merchant-intro"><div className="merchant-avatar"><div className="merchant-hood"><span>◉</span><span>◉</span></div><ShoppingBag className="absolute -bottom-1 -right-2 rounded-full border border-gold/30 bg-[#15101c] p-2 text-gold" size={37} /></div><div><div className="flex items-center gap-2 text-gold"><MessageCircle size={15} /><span className="eyebrow">Mercador errante</span></div><h2 className="section-heading mt-1">Artefatos do reino</h2><p className="mt-2 max-w-sm text-sm leading-relaxed text-mist">“Saudações, aventureiro. Novos artefatos chegaram ao reino.”</p><button className="mt-4 text-xs font-bold uppercase tracking-wider text-gold">Visitar o mercado →</button></div></div><div className="grid min-w-0 flex-1 grid-cols-3 gap-3">{marketItems.map(item => <StoreItemCard key={item.id} item={item} />)}</div></section> }
export const MarketCard = StoreItemCard
