import { Award, Flame, Map, Shield, ShoppingBag, Sparkles, Sword, TrendingUp, type LucideIcon } from 'lucide-react'
import type { ActivityLogEntry, ActivityLogType } from '../types/activity'
export type JournalFilter = 'all' | 'missions' | 'market' | 'achievements' | 'journey' | 'levels' | 'equipment' | 'streak'
const filters: Record<Exclude<JournalFilter,'all'>, ActivityLogType[]> = { missions:['task_completed'], market:['item_purchased'], achievements:['achievement_unlocked','achievement_reward_claimed'], journey:['journey_completed','journey_region_completed'], levels:['level_up'], equipment:['item_equipped'], streak:['streak_milestone'] }
export function matchesJournalFilter(entry: ActivityLogEntry, filter: JournalFilter) { return filter === 'all' || filters[filter].includes(entry.type) }
export function groupActivitiesByDay(entries: ActivityLogEntry[]) { return entries.reduce<Record<string,ActivityLogEntry[]>>((groups,entry)=>{const key=entry.createdAt?.toDate ? entry.createdAt.toDate().toISOString().slice(0,10) : 'unknown';(groups[key]??=[]).push(entry);return groups},{}) }
export function formatActivityDate(value: Date, compact=false) { return new Intl.DateTimeFormat('pt-BR',compact?{day:'2-digit',month:'short'}:{day:'2-digit',month:'long',year:'numeric'}).format(value).toUpperCase() }
export function getActivityIcon(type: ActivityLogType): LucideIcon { if(type==='task_completed')return Sword;if(type==='level_up')return TrendingUp;if(type.startsWith('achievement'))return Award;if(type==='item_purchased')return ShoppingBag;if(type==='item_equipped')return Shield;if(type.startsWith('journey'))return Map;if(type==='streak_milestone')return Flame;return Sparkles }
export function getActivityColor(type: ActivityLogType) { if(type==='task_completed')return'#3b82f6';if(type==='level_up')return'#a855f7';if(type.startsWith('achievement'))return'#f5b942';if(type==='item_purchased')return'#22c55e';if(type==='item_equipped')return'#60a5fa';if(type.startsWith('journey'))return'#d8b4fe';if(type==='streak_milestone')return'#ef4444';return'#aab1c5' }
