import { BrowserRouter, Navigate, Outlet, Route, Routes } from 'react-router-dom'
import { AchievementWatcher } from './components/achievements/AchievementWatcher'
import { Header } from './components/Header'
import { MobileNav } from './components/MobileNav'
import { ProtectedRoute } from './components/ProtectedRoute'
import { Sidebar } from './components/Sidebar'
import { AchievementsPage } from './pages/AchievementsPage'
import { ForgotPasswordPage } from './pages/ForgotPasswordPage'
import { HeroPage } from './pages/HeroPage'
import { InventoryPage } from './pages/InventoryPage'
import { JournalPage } from './pages/JournalPage'
import { JourneyPage } from './pages/JourneyPage'
import { Kingdom } from './pages/Kingdom'
import { LoginPage } from './pages/LoginPage'
import { MarketPage } from './pages/MarketPage'
import { RegisterPage } from './pages/RegisterPage'
import { TasksPage } from './pages/TasksPage'

function GameLayout() { return <div className="min-h-screen bg-ink text-ivory"><Sidebar /><div className="lg:pl-[232px]"><Header /><Outlet /></div><MobileNav /><AchievementWatcher /></div> }
export default function App() { return <BrowserRouter><Routes><Route path="/login" element={<LoginPage />} /><Route path="/cadastro" element={<RegisterPage />} /><Route path="/recuperar-senha" element={<ForgotPasswordPage />} /><Route element={<ProtectedRoute />}><Route element={<GameLayout />}><Route path="/" element={<Kingdom />} /><Route path="/missoes" element={<TasksPage />} /><Route path="/jornada" element={<JourneyPage />} /><Route path="/heroi" element={<HeroPage />} /><Route path="/inventario" element={<InventoryPage />} /><Route path="/mercado" element={<MarketPage />} /><Route path="/conquistas" element={<AchievementsPage />} /><Route path="/diario" element={<JournalPage />} /></Route></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter> }
